version: '3.7'
services:
  backend:
    image: spotify-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    container_name: spotify-backend
    env_file:
      - .env.production
    depends_on:
      - database
    networks:
      - spotify-network
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    container_name: spotify-database
    env_file:
      - .env.production
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spotify-network

volumes:
  postgres:
    driver: local

networks:
  spotify-network:
    driver: bridge